#!/bin/bash
# OpenCV environment template
# This file is auto-generated by build_opencv.sh or install_opencv_portable.sh
# Do not edit manually - regenerate by running the install script.
#
# Usage: source ~/opencv-install/opencv-env.sh

# ─── Configuration ───────────────────────────────────────────────────────────
# Adjust OPENCV_DIR if you installed to a different location
export OPENCV_DIR="${HOME}/opencv-install"

# ─── Environment Variables ───────────────────────────────────────────────────
export LD_LIBRARY_PATH="${OPENCV_DIR}/lib:${LD_LIBRARY_PATH:-}"
export PKG_CONFIG_PATH="${OPENCV_DIR}/lib/pkgconfig:${PKG_CONFIG_PATH:-}"
export PYTHONPATH="${OPENCV_DIR}/lib/python3.10/site-packages:${PYTHONPATH:-}"
export PATH="${OPENCV_DIR}/bin:${PATH}"
export CMAKE_PREFIX_PATH="${OPENCV_DIR}:${CMAKE_PREFIX_PATH:-}"

echo "OpenCV environment loaded from ${OPENCV_DIR}"
